language: cpp
compiler:
  - gcc
  - clang
before_script:
	- sudo apt-get install automake
script:
  - ./configure
  - make
branches:
  only:
    - master
notifications:
  recipients:
    - ivo@zuidstijl.nl
  email:
    on_success: change
    on_failure: always
