language: cpp
compiler:
  - gcc
  - clang
before-script:
  - autotools --reconf
script:
  - ./configure
  - make
branches:
  only:
    - master
notifications:
  recipients:
    - ivo@zuidstijl.nl
  email:
    on_success: change
    on_failure: always
