language: cpp
compiler:
  - gcc
  - clang
before_script:
  - sudo apt-get install libcppunit*
  - ./autogen.sh
script:
  - make && make check
branches:
  only:
    - master
notifications:
  recipients:
    - ivo@zuidstijl.nl
  email:
    on_success: change
    on_failure: always
