language: cpp
compiler:
  - gcc
  - clang
before_script:
  - ./configure
script:
	- make
branches:
  only:
    - master
notifications:
  recipients:
    - ivo@zuidstijl.nl
  email:
    on_success: change
    on_failure: always
